site_name: K.I.S.S
site_url: https://yorks.github.io/mywiki/
repo_url: https://github.com/yorks/mywiki
repo_name: GitHub

theme:
  name: material
  language: zh-CN
  features:
    - navigation.tabs        # 顶部导航栏
    - navigation.tracking    # URL随滚动变化
    - navigation.indexes     # 文件夹可点击
    - toc.follow            # 侧边目录跟随
    - content.code.copy     # 代码块复制按钮
  palette:
    - scheme: default       # 默认亮色模式
      primary: teal         # 主题色
      accent: purple
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate         # 暗色模式
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: 切换至亮色模式

# 插件配置
plugins:
  - search
  - blog:
      blog_dir: blog        # 博客文章存放目录
      post_date_format: date
  - tags

markdown_extensions:
  - admonition              # 提示块支持
  - pymdownx.highlight:     # 代码高亮
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
